apiVersion: apps/v1
kind: Deployment
metadata:
  name: gr4dp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gr4dp
  template:
    metadata:
      labels:
        app: gr4dp
    spec:
      containers:
      - name: gr4dp
        image: gr4dp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 1
